# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               CppThings
tagline:             'Everyday C++ stuff'
description:         'Blog about day to day C++ programming.'
url:                 http://cppthings.github.io/
baseurl:             'http://cppthings.github.io/'
paginate:            5

# About/contact
author:
  name:              Florian Chevassu
  url:               https://twitter.com/FlorianChevassu
  email:             chevassu.florian@gmail.com

# Custom vars
version:             1.0.0
